import { DEFAULT_STRATEGY, type StrategyConfig } from '../config/schema.js';

/**
 * Shipped presets (instructions.md §6.6). These mirror the reference UI's
 * PRESETS so selecting one in the panel and on the backend agree.
 */
export const PRESETS: Record<string, StrategyConfig> = {
  Conservative: {
    ...DEFAULT_STRATEGY,
    sources: ['pumpswap_pool'],
    phases: ['post_grad'],
    reqUpdateRevoked: true,
    maxDevPct: 3,
    maxTop10Pct: 22,
    maxSinglePct: 10,
    maxBundlePct: 12,
    minHolders: 60,
    minLiqUsd: 15000,
    maxRugScore: 20,
    solPerToken: 0.1,
    maxSlippage: 6,
    feeAggr: 1,
    jito: false,
    maxConcurrent: 3,
    dailyCapSol: 1,
    tpLadder: '120:100',
    stopLoss: 25,
    trailing: 0,
    maxHoldMin: 45,
    liqDropExit: 30,
    aggrTP: false,
    aggrTrigger: 80,
    aggrSellPct: 50,
    fastExit: false,
  },
  Balanced: { ...DEFAULT_STRATEGY },
  Degen: {
    ...DEFAULT_STRATEGY,
    sources: ['pumpfun_curve', 'pumpswap_pool'],
    phases: ['new_mint', 'mid_curve', 'at_grad'],
    tokenProgram: 'allow_t22',
    reqLpBurned: false,
    maxDevPct: 12,
    maxTop10Pct: 45,
    maxSinglePct: 22,
    maxBundlePct: 30,
    minHolders: 5,
    minLiqUsd: 0,
    maxBuyTax: 5,
    maxSellTax: 5,
    maxRugScore: 60,
    solPerToken: 0.5,
    maxSlippage: 25,
    feeAggr: 4,
    jito: true,
    maxConcurrent: 8,
    dailyCapSol: 4,
    tpLadder: '100:50, 400:25, 1000:15',
    stopLoss: 40,
    trailing: 20,
    maxHoldMin: 20,
    liqDropExit: 50,
    aggrTP: true,
    aggrTrigger: 25,
    aggrSellPct: 90,
    fastExit: true,
  },
  Copy: {
    ...DEFAULT_STRATEGY,
    sources: ['pumpfun_curve', 'pumpswap_pool', 'raydium_pool'],
    phases: ['new_mint', 'mid_curve', 'at_grad', 'post_grad'],
    // copyTrade list supplied by the user; safety chain still runs
    maxRugScore: 50,
    tpLadder: '150:50, 500:25',
  },
  'Graduation snipe': {
    ...DEFAULT_STRATEGY,
    sources: ['pumpswap_pool'],
    phases: ['at_grad'],
    curveMin: 90,
    curveMax: 100,
    maxDevPct: 8,
    maxTop10Pct: 35,
    maxSinglePct: 18,
    maxBundlePct: 25,
    minHolders: 15,
    minLiqUsd: 9000,
    maxRugScore: 40,
    solPerToken: 0.3,
    maxSlippage: 15,
    feeAggr: 3,
    jito: true,
    dailyCapSol: 3,
    tpLadder: '80:60, 300:25',
    stopLoss: 30,
    trailing: 18,
    maxHoldMin: 15,
    liqDropExit: 45,
    aggrTP: true,
    aggrTrigger: 35,
    aggrSellPct: 85,
    fastExit: true,
  },
};
